version: '3.7'

services:
  web:
    build: .
    image: djecommerce:0.1
    container_name: web
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/Djcommerce/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
